version: '3'

services:
  tpdb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONITORED_FOLDER=/path/to/your/folder
    volumes:
      - /path/to/your/folder:/app/input
